name: CI

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run TS Hello Action
        uses:  nookyo/qubership-workflow-hub/actions/chart-release-action@main
        with:
          name: 'World'