name: Cleanup Old Docker Images

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight
  workflow_dispatch:
    inputs:
      threshold-days:
        description: "Number of days to keep container versions"
        required: false
        default: "7"
      included-tags:
        description: "Tags to include for deletion"
        required: false
        default: "dev*"
      excluded-tags:
        description: "Tags to exclude from deletion"
        required: false
        default: "release*"
      dry-run:
        description: "Enable dry-run mode"
        type: boolean
        required: false
        default: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Container Package Cleanup Action
        uses: Netcracker/qubership-workflow-hub/actions/container-package-cleanup@main
        with:
          threshold-days: 0
          included-tags: 'dev*'
          excluded-tags: 'release*'
          dry-run: ${{ github.event.inputs.dry-run }}
        env:
          PACKAGE_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}